apiVersion: v1
kind: ConfigMap
metadata:
  name: name-service
data:
  application.properties: |-
    server.port=8080
    # disable all management enpoints except health
    endpoints.enabled = false
    endpoints.health.enabled = true
    management.health.defaults.enabled=false
    camel.health.enabled=false
    camel.health.indicator.enabled=true
    jaeger.reporter.endpoint=http://jaeger-collector.istio-system.svc:14268/api/traces