apiVersion: v1
kind: ConfigMap
metadata:
  name: name-service
data:
  application.properties: |-
    server.port=8080

    jaeger.reporter.endpoint=http://jaeger-collector.istio-system.svc:14268/api/traces

    # disable health defaults
    management.health.defaults.enabled=false

    camel.health.enabled=false
    camel.health.indicator.enabled=true
