apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: name-service
    provider: jkube
    group: com.redhat.fuse.boosters.tracing
  name: name-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: name-service
    provider: jkube
    group: com.redhat.fuse.boosters.tracing
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: true
      labels:
        app: name-service
        provider: jkube
        group: com.redhat.fuse.boosters.tracing
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: name-service
      containers:
      - name: name-service
        volumeMounts:
          - name: config-volume
            mountPath: /deployments/application.properties
            subPath: application.properties
