apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: greetings-service
    provider: jkube
    group: com.redhat.fuse.boosters.tracing
  name: greetings-service
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    app: greetings-service
    provider: jkube
    group: com.redhat.fuse.boosters.tracing
  strategy:
    rollingParams:
      timeoutSeconds: 3600
    type: Rolling
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: true
      labels:
        app: greetings-service
        provider: jkube
        group: com.redhat.fuse.boosters.tracing
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: greetings-service
      containers:
      - name: greetings-service
        env:
          - name: NAME_SERVICE_SERVICE_HOST
            value: "name-service"
          - name: NAME_SERVICE_SERVICE_PORT
            value: "8080"
        volumeMounts:
          - name: config-volume
            mountPath: /deployments/application.properties
            subPath: application.properties
